source "https://rubygems.org"

gem "fastlane", '2.187.0'
# gem 'rest-client', '~> 2.1'
gem 'aws-sdk', '~> 3'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
