-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyvbyoSXbQH9avdVx
gzXndvVle9w4LovEJ4I1xmm5IwugCgYIKoZIzj0DAQehRANCAAT0rn3WRxtQhV8S
iHS1rSINfRFsk1g2vQKiyWVPhtJcXmhWVKNtlQvjtaX2WakzygfqFJ8qySncxSFP
NKqcNb6l
-----END PRIVATE KEY-----