name: Processing release
on: 
  release:
    types: [published]

jobs:   
  communicate-on-pull-request-released:
    name: communicate on pull request released
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - name: Communicate on PR released
      uses: fastlane/github-actions/communicate-on-pull-request-released@latest
      with:
        repo-token: ${{ secrets.BOT_GITHUB_TOKEN }}
